name: locationiq_autocomplete_flutter
description: A Flutter autocomplete TextField + suggestions dropdown for LocationIQ (pure HTTP client included).
version: 0.1.0
homepage: https://github.com/iZenrix/locationiq_autocomplete_flutter
repository: https://github.com/iZenrix/locationiq_autocomplete_flutter
issue_tracker: https://github.com/iZenrix/locationiq_autocomplete_flutter/issues
topics:
  - locationiq
  - autocomplete
  - geocoding
  - places
  - flutter

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
